---
title: "City Info"
author: "Spencer Rhea"
date: "8/27/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(include = FALSE)
library(raster)
library(feather)
library(tidyverse)
library(stringr)
library(ggpubr)
library(viridis)
library(sf)
library(FedData)
library(mapview)
library(lubridate)
library(feather)
library(tidycensus)
library(USAboundaries)
library(ggthemes)
library(ggplot2)
library(kableExtra)
library(knitr)
library(tmap)
library(tmaptools)
library(RColorBrewer)
library(nhdplusTools)
```


```{r}
census <- read_rds("/Users/spencerrhea/Google Drive/EJ_paper /data/census.rds") %>%
  st_transform(2163)

city_geom <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area", variables = "B01003_001", year = 2013, geometry = T) %>%
  filter(NAME %in% c("Fort Collins, CO Metro Area", "Boulder, CO Metro Area", "Denver-Aurora-Lakewood, CO Metro Area", "Colorado Springs, CO Metro Area", "Pueblo, CO Metro Area")) %>%
  st_transform(2163)

denver_metro <- c(' Denver County',  ' Arapahoe County', ' Jefferson County', ' Adams County', ' Douglas County', ' Broomfield County', ' Elbert County', ' Park County', ' Clear Creek County',  ' Gilpin County')

```

```{r}
census_name <- census %>%
  separate_rows(NAME, sep = ',') %>%
  filter(NAME %in% c(denver_metro, ' Larimer County', ' Boulder County', ' El Paso County', ' Pueblo County')) %>%
  mutate(place = case_when(NAME %in% denver_metro ~ 'Denver',
                           NAME == ' Larimer County' ~ 'Fort_Collins',
                           NAME == ' Boulder County' ~ 'Boulder',
                           NAME == ' El Paso County' ~ 'Colorado_Springs',
                           NAME == ' Pueblo County' ~ 'Pueblo'))

city_summary <- census_name %>%
  mutate(weighted_income = median_income*population) %>%
  group_by(place) %>%
  summarize(color = sum(color, na.rm = T),
            total = sum(population, na.rm = T),
            percent_color = (color/total)*100,
            renters = sum(renters, na.rm = T),
            tenure_total = sum(tenure_total, na.rm = T),
            degrees = sum(degrees, na.rm = T),
            income = sum(weighted_income, na.rm = T)/sum(total),
            education = sum(education_25_total, na.rm = T),
            percent_renters = sum(renters, na.rm = T)/sum(tenure_total, na.rm = T),
            percent_degree = sum(degrees, na.rm = T)/sum(education_25_total, na.rm = T),
            age = mean(median_age, na.rm = T),
            gini = mean(estimate_gini_index, na.rm = T),
            percent_black = (sum(estimate_black, na.rm = T)/sum(population, na.rm = T))*100,
            percent_hispanic = (sum(estimate_hispanic, na.rm = T)/sum(population))*100,
            percent_asain = (sum(estimate_asian, na.rm = T)/sum(population, na.rm = T))*100,
            percent_native = (sum(estimate_native, na.rm = T)/sum(population, na.rm = T))*100,
            percent_other_mixed = (sum(estimate_other, na.rm = T)+sum(estimate_two_or_more))/sum(population, na.rm = T)*100,
            percent_hawaiian = sum(estimate_hawaiian, na.rm = T)/sum(population, na.rm = T)*100) %>%
  select(-color, -renters, -degrees, -education, -age, -gini, -tenure_total) %>%
  ungroup() %>%
  rename(Population = total)

city_summary <- arrange(city_summary, desc(percent_degree)) %>%
  as.data.frame() %>%
  select(-geometry) %>%
  rename(Metro_area = place) 

write_csv(city_summary, 'data_out/city_info.csv')
```

