---
title: "nhd_play"
author: "Spencer Rhea"
date: "5/27/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(feather)
library(nlc)
library(tidyverse)
library(stringr)
library(viridis)
library(sf)
library(FedData)
library(mapview)
library(lubridate)
library(feather)
library(tidycensus)
library(USAboundaries)
library(ggthemes)
library(ggplot2)
library(kableExtra)
library(knitr)
library(tmap)
library(tmaptools)
library(ColorBrewer)
library(RColorBrewer)
library(nhdplusTools)
```

# E.coli data 
```{r cars}
ecoli_raw <- read_feather("wq_data/Colorado_ecoli.feather")

inv <- read_feather('wq_data/test/wqp_inv.feather') %>%
    select(SiteID=MonitoringLocationIdentifier,
           resultCount,
           parameter,
                  lat,
                  lon) %>%
  distinct() %>%
  filter(!is.na(lat),
         !is.na(lon)) %>%
  st_as_sf(.,coords=c('lon','lat'),crs=4326) %>%
  distinct(SiteID)


clean_ecoli <-  ecoli_raw %>%
                  dplyr::select(date=ActivityStartDate,
                         parameter=CharacteristicName,
                         units=ResultMeasure.MeasureUnitCode,
                         SiteID=MonitoringLocationIdentifier,
                         org=OrganizationFormalName,
                         org_id=OrganizationIdentifier,
                         time=ActivityStartTime.Time,
                         raw_value=ResultMeasureValue,
                         sample_method=SampleCollectionMethod.MethodName,
                         analytical_method=ResultAnalyticalMethod.MethodName,
                         particle_size=ResultParticleSizeBasisText,
                         date_time=ActivityStartDateTime,
                         media=ActivityMediaName,
                         sample_depth=ActivityDepthHeightMeasure.MeasureValue,
                         sample_depth_unit=ActivityDepthHeightMeasure.MeasureUnitCode,
                         fraction=ResultSampleFractionText,
                         status=ResultStatusIdentifier) %>%
  mutate(units = trimws(units)) %>%
  #Keep only samples that are water samples
  filter(media=='Water') %>%
  filter(units != "ug/l")

# Removed filter for log mean 
ecoli_mean <- clean_ecoli %>%
  filter(year(date) >= 2005 & year(date) <= 2015) %>%
  filter(parameter == "Escherichia coli") %>%
  group_by(SiteID) %>%
  summarize(mean = mean(raw_value,na.rm=T) %>% round(.,2),
            raw_mean = mean(raw_value,na.rm=T),
            sd = sd(raw_value, na.rm = T),
            count=n()) %>%
  filter(count > 9) %>% 
  #filter(sd < 5) %>%
  mutate(log_mean=log10(mean)) %>%
  filter(log_mean > 0.0000001)

ecoli_mean_sf <- inv %>%
  right_join(.,ecoli_mean,by='SiteID') %>%
  st_transform(2163) 

ecoli_mean_sf_3km <- ecoli_mean_sf %>%
  st_buffer(3000)

ecoli_mean_sf_100m <- ecoli_mean_sf %>%
  st_buffer(100)
```

# WWTP 
```{r}
#Read in data from EPA's facility registration service, downloaded from EPA website 
wastewater <- st_read(dsn = "wastewater/CWA_summaries_060314.gdb")

st_layers("wastewater/CWA_summaries_060314.gdb")

wastewater <- wastewater %>%
  filter(CWP_STATE == "CO")

co <- us_states(states = "CO")

#convert dataframe into spatial object 
waste_water_full <- wastewater %>%
  st_as_sf(coords = c("coords.x1", "coords.x2"), crs = "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs") %>%
  filter(CWP_STATE == "CO") 

#filter to only WWTP and remove permits that are no longer active
sewage <- waste_water_full %>%
  filter(SIC_CODES == 4952) %>%
  filter(CWP_PERMIT_STATUS_DESC != "Terminated") %>%
  mutate(type = "plant") %>%
  filter(CWP_PERMIT_STATUS_DESC != "Expired") %>%
  st_transform(2163) 

write_rds(sewage, "clean_data/sewage_plants.rds")


#Flow 


wwtp_flow <- read_csv("wwtp_flow.csv") 

wwtp_flow <- wwtp_flow %>%
  filter(State == "CO")

wwtp_loc <- read_rds("sewage_plants.rds")
```

# South Platte 
## nhd 
```{r}
sp_start <- st_sfc(st_point(c(-104.603644, 40.416362)), crs = 4269)
sp_comid <- discover_nhdplus_id(sp_start)

sp_flowline <- navigate_nldi(list(featureSource = "comid", 
                               featureID = sp_comid), 
                          mode = "upstreamTributaries", 
                          data_source = "")


sp_subset <- subset_nhdplus(comids = sp_flowline$nhdplus_comid,
                         output_file = "nhd/subset.gpkg",
                         nhdplus_data = "download", 
                         return_data = TRUE, 
                         overwrite = T)


sp_flowline <- sp_subset$NHDFlowline_Network
sp_catchment <- sp_subset$CatchmentSP
sp_waterbody <- sp_subset$NHDWaterbody


platte <- sp_flowline %>%
  filter(gnis_name == "South Platte River")

sp_prep <- prepare_nhdplus(sp_flowline, min_network_size = 10, min_path_length = 10) %>%
  select(ID = COMID, toID = toCOMID, length = LENGTHKM)

sp_pathlength <- get_pathlength(sp_prep)

sp_length <- sp_flowline %>%
  rename(ID = comid) %>%
  right_join(sp_pathlength, by = "ID")

platte <- sp_length %>%
  filter(gnis_name == "South Platte River") %>%
  st_transform(4269) %>%
  select(-pathlength.x) %>%
  rename(pathlength = pathlength.y)
```

# Landcover 
## Load in national landcover map and subset 
```{r}
nlcd <- raster("nlcd/NLCD_2016.img") 

co <- us_states(states = "CO") %>%
  st_transform(5070)

nlcd_co <- crop(nlcd, co)

codes <- nlcd_co@data@attributes[[1]][["NLCD.Land.Cover.Class"]]

legend <- as_data_frame(codes) %>%
  mutate(id = row_number()) %>%
  rename(type = value)  %>%
  mutate(land = ifelse(type == "", NA, type)) %>%
  filter(!is.na(land)) %>%
  select(-land) %>%
  mutate(type = as.character(type)) %>%
  mutate(id = id-1)
```

# Get percentages for river segments 
## Approach one (not working)
```{r}
land_use <- function(loc, flow_line = flowline, watersheds = catchment, nlcd_object = nlcd_crop) {

up_stream <- get_UT(flow_line, loc)

up_segments <- flow_line %>%
  filter(comid %in% up_stream)

catch <- watersheds %>%
  filter(featureid %in% pull(up_segments, comid)) %>%
  st_transform(5070)

whole_catch <- try(st_union(catch) %>%
  st_sf())

if(class(whole_catch)[1] != "try-error"){ 

catch_extent <- extent(whole_catch)

nlcd_crop <- crop(nlcd_object, catch_extent) 

nlcd_mask <- mask(nlcd_crop, whole_catch) 

nlcd_trim <- trim(nlcd_mask) 

values <- as.data.frame(getValues(nlcd_trim)) %>%
  rename(id = 1) %>%
  group_by(id) %>%
  summarise(num = n()) %>%
  filter(id != 0) %>%
  left_join(legend) %>%
  filter(!is.na(id)) 

total <- sum(values$num)

final <- values %>%
  mutate(percent = (num/total)*100) %>%
  mutate(comid = loc) %>%
  select(comid, percent, land_cover=type) %>%
  pivot_wider(names_from = land_cover, values_from = percent) 
}

else{print(paste(loc, " failed to load", sep = ""))}
}

```

## Approach 2
### Landcover by catchemnt 
```{r}
nlcd_object <- nlcd_co
#Get land cover for every catchment 
sp_catchment_id <- sp_catchment %>%
  mutate(row = row_number())

whole_catch <- sp_catchment_id

define_land_by_catch <- function(catch, row) {

whole_catch <- catch[row,] %>%
  st_transform(5070)

fetid <- pull(whole_catch, featureid)
    
catch_extent <- extent(whole_catch)

nlcd_crop <- crop(nlcd_object, catch_extent) 

nlcd_mask <- mask(nlcd_crop, whole_catch) 

nlcd_trim <- trim(nlcd_mask) 

values <- as.data.frame(getValues(nlcd_trim)) %>%
  rename(id = 1) %>%
  group_by(id) %>%
  summarise(num = n()) %>%
  filter(id != 0) %>%
  full_join(legend) %>%
  filter(!is.na(id))%>%
  mutate(featureid = fetid) %>%
  select(-id) 

total <- sum(values$num, na.rm = T)

fin <- values %>%
  pivot_wider(names_from = type, values_from = num) %>%
  mutate(Total = total)
}

# Us function 
landcover_by_catchment <- define_land_by_catch(sp_catchment_id, 1)

seq <- 1:4129
for(i in seq) {
  x <- i+1
  shed <- define_land_by_catch(sp_catchment_id, x)
  
  landcover_by_catchment <- rbind(landcover_by_catchment, shed)
}
```

### Percentages for river segments 
```{r}
#get percent land cover along river network 
percecnt_along <- function(river_comid, flow_lines = flowline, watersheds = landcover_by_catchment) {


up_stream <- get_UT(flow_lines, river_comid)

up_segments <- flow_lines %>%
  filter(comid %in% up_stream)

catch <- watersheds %>%
  filter(featureid %in% pull(up_segments, comid)) %>%
  pivot_longer(cols = c("Evergreen Forest", "Shrub/Scrub", "Unclassified", "Open Water", "Perennial Snow/Ice", "Developed, Open Space", "Developed, Low Intensity", "Developed, Medium Intensity", "Developed, High Intensity", "Barren Land", "Deciduous Forest", "Mixed Forest", "Herbaceuous", "Hay/Pasture", "Cultivated Crops", "Woody Wetlands", "Emergent Herbaceuous Wetlands")) %>%
  group_by(name) %>%
  summarise(num = sum(value, na.rm = T)) %>%
  mutate(num = as.numeric(num)) 

total <- sum(catch$num) 

final <- catch %>%
  mutate(Total = total) %>%
  mutate(percent = (num/Total)*100) %>%
  mutate(percent = round(percent, 5)) %>%
  select(name, percent) %>%
  mutate(comid = river_comid) %>%
  pivot_wider(names_from = name, values_from = percent)
}

#use loop to do for all river segments 
platte_comids <- pull(platte, ID)

percents <- percecnt_along(platte_comids[1])

seq <- 1:157
for(i in seq) {
  new <- percecnt_along(platte_comids[i+1]) 
  
  percents <- rbind(new, percents)
}

percent_along_river <- percents %>%
  rename(barren = 2,
         crops = 3,
         deciduous = 4,
         developed_high = 5,
         developed_low = 6,
         developed_mid = 7,
         developed_open = 8,
         wetland_herbaceous = 9,
         evergreen = 10,
         hay_pasture = 11,
         herbaceous = 12,
         forest_mixed = 13,
         water = 14,
         ice = 15,
         shrub = 16,
         wetland_wood = 18) %>%
  select(-Unclassified)

landcover_sumz <- percent_along_river %>%
  mutate(developed = developed_high+developed_low+developed_mid,
         forest = forest_mixed+deciduous+evergreen,
         wetland = wetland_herbaceous+wetland_wood,
         agriculture = crops+hay_pasture) %>%
  select(-developed_high, -developed_mid, -developed_low, -forest_mixed, -deciduous, -evergreen, -wetland_herbaceous, -wetland_wood, -crops, - hay_pasture) 
```


# Join wwtp and river 
```{r}
platte_trans <- platte %>%
  mutate(pathlength = 281.122-pathlength) %>%
  rename(comid = ID) 


filter_sp_wwtp <- sewage %>%
  filter(STATE_WATER_BODY_NAME %in% c("SOUTH PLATTE RIVER", "South Platte River", "storm sewer-South Platte River"))

sp_wwtp_buff <- filter_sp_wwtp %>%
  st_buffer(250)

sp_wwtp <- st_join(platte_trans, sp_wwtp_buff) %>%
  filter(!is.na(CWP_NAME))

sp_sweage_codes <- sp_wwtp %>%
  pull(pathlength)

```

## Join E.coil to landcover 
```{r}
platte_trans <- platte %>%
  mutate(pathlength = 281.122-pathlength) %>%
  rename(comid = ID) 

sp_jumps <- st_join(platte_trans, ecoli_mean_sf_100m)

sp_jumps_fil <- sp_jumps %>%
  as.data.frame() %>%
  full_join(landcover_sumz, by = "comid") %>%
  select(-geometry) %>%
  filter(!is.na(pathlength)) %>%
  select(pathlength, mean, herbaceous, shrub, developed, forest, wetland, agriculture) %>%
  mutate(mean = mean/50) %>%
   pivot_longer(cols = c(herbaceous, shrub, developed, forest, wetland, agriculture))

ggplot(sp_jumps_fil, aes(x = pathlength, y = value, colour = name)) +
  geom_line() +
  geom_point(aes(x = pathlength, y = mean)) +
  scale_color_manual(values = c("#252525", "#e7298a", "#66a61e", "#7570b3", "#d95f02", "#1b9e77"), 
                     breaks = c("herbaceous", "shrub", "forest", "wetland", "agriculture", "developed"),
                     name = "Landcover") +
  scale_y_continuous(sec.axis = sec_axis(trans = ~.*50,  name = "E.coli (#/ml)")) +
  theme_few() +
  geom_vline(xintercept = sp_sweage_codes) +
  labs(x = "Length on River", y = "Watershed landcover (%)")


#ag, developed, forest, herb, shrub, wet
```






# Get length of river 
```{r}
pull_flowline <- function(start_lat, start_long, river_name) {
  
start_point <- st_sfc(st_point(c(start_long, start_lat)), crs = 4269)
start_comid <- discover_nhdplus_id(start_point)

flowline <- navigate_nldi(list(featureSource = "comid", 
                               featureID = start_comid), 
                          mode = "upstreamTributaries", 
                          data_source = "")

path <- paste("nhd/", river_name, ".gpkg", sep = "")


subset <- subset_nhdplus(comids = flowline$nhdplus_comid,
                         output_file = path,
                         nhdplus_data = "download", 
                         return_data = TRUE, 
                         overwrite = T)


flowline <- subset$NHDFlowline_Network


preped <- prepare_nhdplus(flowline, min_network_size = 10, min_path_length = 10)

fl <- dplyr::select(preped,
ID = COMID, toID = toCOMID, length = LENGTHKM)

look <- get_pathlength(fl)

length <- flowline %>%
  select(ID = comid, gnis_name) %>%
  right_join(look)

river_length <- length %>%
  filter(gnis_name == river_name) %>%
  st_transform(4269) 

max_val <- max(river_length$pathlength, na.rm = T) 

final <- river_length %>%
  mutate(pathlength = (pathlength - max_val)*-1)
  

return(final)
}
```

## South Platte 
```{r}
s_platte <- pull_flowline(40.416362, -104.603644, "South Platte River")

mapview(s_platte, zcol = "pathlength")
```

## Poudre River 
```{r}
poudre <- pull_flowline(40.424403, -104.601064, "Cache la Poudre River")
 
mapview(poudre, zcol = "pathlength") 
```

## Fountain Creek 
```{r}
fountain <- pull_flowline(38.254751, -104.590327, "Fountain Creek")

mapview(fountain, zcol = "pathlength") 
```



# CAT
```{r}
cat_files <- list.files("cat/", full.names = T)
ad_mi_slopes <- read_csv(cat_files[1]) %>%
  full_join(read_csv(cat_files[2]))
```

